from abc import ABC, abstractmethod


class VPSProvider(ABC):
    @abstractmethod
    def create_vps(self, spec: dict) -> dict: ...
    @abstractmethod
    def delete_vps(self, provider_id: str) -> None: ...
    @abstractmethod
    def start_vps(self, provider_id: str) -> None: ...
    @abstractmethod
    def stop_vps(self, provider_id: str) -> None: ...
    @abstractmethod
    def restart_vps(self, provider_id: str) -> None: ...
    @abstractmethod
    def rebuild_vps(self, provider_id: str, os_name: str) -> None: ...
    @abstractmethod
    def get_vps(self, provider_id: str) -> dict: ...
    @abstractmethod
    def get_metrics(self, provider_id: str) -> dict: ...
    @abstractmethod
    def execute_command(self, provider_id: str, command: list[str]) -> tuple[int, str]: ...
